### ISSUE TITLE
ERROR: encountered exception 'Uncaught' (122:21)

### ISSUE THREAD

**Issue by Pradeep-upadhya** [lawzava/scrape#1]
In the below code when I set JSWait `true` then it returns the output with the error in the console:

```
ERROR: encountered exception 'Uncaught' (122:21)
```

If I set JSWait to `false` then It will not show any error.

```go
em := []string{}
p := scraper.Parameters{
    Async:               true,
    Emails:              true,
    FollowJSWaitExternalLinks: false,
    JSWait:              true,
    MaxDepth:            9,
    PrintLogs:           isDevelopment(),
    Recursively:         false,
    Website:             website,
}
s := scraper.New(p)
err := s.Scrape(&em)
```
Why I am getting this error?

Is it possible to suppress the mentioned error with `JSWait true`?

**Comment by lawzava** [comment]
@Pradeep-upadhya Thank you for raising this issue. I apologise for the delay. 

I was unable to replicate it, could you share the site that you tried to scrape?

Also, logs suppression for `--js-wait` has just been pushed. Please tell me if that helps.

**Comment by lawzava** [comment]
@Pradeep-upadhya I'm closing this for now. Please open a new issue with more details if this bug persists. 

Thank you!
