### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by storopoli** [lawzava/scrape#14]
We already have a nice linux installation with snap, I am missing a mac installation with Homebrew.

Is it possible?

**Comment by lawzava** [comment]
Sure! I'll look into it 👍🏼 

Thanks for the suggestion

**Comment by storopoli** [comment]
I could help you out but I am not familiar with Ruby language that Homebrew uses to create formulae.

**Comment by lawzava** [comment]
No worries. When you cover your eyes a bit to ignore poor UX with adding new packages it's pretty straightforward. 😄

**Comment by lawzava** [comment]
Done @storopoli 

xcode was another kind of hell, thus the delay.. 😢 

```
brew tap lawzava/scrape https://github.com/lawzava/scrape
brew install scrape
```

**Comment by storopoli** [comment]
Wow amazing! Thanks!
