### ISSUE TITLE
Error: can't scrape sites with http://

### ISSUE THREAD

**Issue by GabrielAlbinsson** [lawzava/scrape#5]
Tried to scrape site:
`./scrape -w "http://sneakycorp.htb" --debug`

Got result:

> [000001] 1 [     1 - request] map["url":"https://sneakycorp.htb"] (50.331µs)
> [000002] 1 [     1 - error] map["status":"" "url":"https://sneakycorp.htb"] (53.622255ms)

There is no HTTPS server.

**Comment by lawzava** [comment]
fixed in https://github.com/lawzava/scrape/pull/6
